### ISSUE TITLE
Pseudocodice disjoint paths [Algoritmo 7 p 30]

### ISSUE THREAD

**Issue by S3gmentati0nFault** [sgorblex-unimi/algocomp#2]
Da migliorare il modo in cui lo pseudocodice è stato scritto, in particolare il commento e le righe 6 - 7 sono, secondo me, totalmente incomprensibili.
Un esempio di come si potrebbero migliorare:

```
for i in k && !found {
        pi_i = find the shortest path connecting (s_i, t_i) with i not in I;
        if pi_i != nullptr {
                found = true;
        }
}
if(!found){
        break;
}
```

**Comment by S3gmentati0nFault** [comment]
In realtà nemmeno quello sopra va proprio bene perchè prende il primo e non il minimo totale, ho capito adesso che cosa voleva dire il professore con la sua notazione, vuole prendere il più corto tra gli shortest paths che non sono ancora stati inclusi nella soluzione, bisognerebbe renderla in questo modo che altrimenti si fa fatica a capire.

**Comment by sgorblex** [comment]
In effetti questa cosa è stata risolta molte versioni fa. Chiedo scusa, chiudo solo ora.
